default: &default
  adapter:  <%= ENV["DATABASE_ADAPTER"] %>
  database: <%= ENV["DATABASE_NAME"] %>
  encoding: <%= ENV["DATABASE_ENCODING"] %>
  pool:     <%= ENV["DATABASE_POOL"] %>
  timeout:  <%= ENV["DATABASE_TIMEOUT"] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
