default: &default
  adapter:  <%= ENV["DATABASE_ADAPTER"] %>
  encoding: <%= ENV["DATABASE_ENCODING"] %>
  pool:     <%= ENV["DATABASE_POOL"] %>
  timeout:  <%= ENV["DATABASE_TIMEOUT"] %>

development:
  <<: *default
  database: <%= motley_development

test:
  <<: *default
  database: motley_test

production:
  <<: *default
  database: motley_production
